-- MySQL Script generated by MySQL Workbench
-- Sun Jun 22 11:05:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco_mercado
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco_mercado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco_mercado` ;
USE `banco_mercado` ;

-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `endereco` VARCHAR(100) NULL,
  `foto` VARCHAR(255) NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`categoria` (
  `idcategoria` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_produto` (
  `idproduto` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `valor` DECIMAL NULL,
  `estoque` INT NULL,
  `descricao` VARCHAR(200) NULL,
  `status` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`idproduto`, `categoria_idcategoria`),
  INDEX `fk_tb_produto_categoria1_idx` (`categoria_idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_categoria1`
    FOREIGN KEY (`categoria_idcategoria`)
    REFERENCES `banco_mercado`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_pagamento` (
  `idtb_pagamento` INT NOT NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  `pagamento` VARCHAR(45) NULL,
  `data_pagamento` VARCHAR(45) NULL,
  PRIMARY KEY (`idtb_pagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_pedido` (
  `idpedido` INT NOT NULL AUTO_INCREMENT,
  `valor_total` DECIMAL(10,2) NULL,
  `data` DATE NULL,
  `tb_cliente_idcliente` INT NOT NULL,
  `tb_pagamento_idtb_pagamento` INT NOT NULL,
  PRIMARY KEY (`idpedido`, `tb_cliente_idcliente`),
  INDEX `fk_tb_pedido_tb_cliente1_idx` (`tb_cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_tb_pedido_tb_pagamento1_idx` (`tb_pagamento_idtb_pagamento` ASC) VISIBLE,
  CONSTRAINT `fk_tb_pedido_tb_cliente1`
    FOREIGN KEY (`tb_cliente_idcliente`)
    REFERENCES `banco_mercado`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pedido_tb_pagamento1`
    FOREIGN KEY (`tb_pagamento_idtb_pagamento`)
    REFERENCES `banco_mercado`.`tb_pagamento` (`idtb_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  `tipo` CHAR(1) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco_mercado`.`tb_cliente_has_tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco_mercado`.`tb_cliente_has_tb_produto` (
  `tb_cliente_idcliente` INT NOT NULL,
  `tb_produto_idproduto` INT NOT NULL,
  `tb_produto_categoria_idcategoria` INT NOT NULL,
  PRIMARY KEY (`tb_cliente_idcliente`, `tb_produto_idproduto`, `tb_produto_categoria_idcategoria`),
  INDEX `fk_tb_cliente_has_tb_produto_tb_produto1_idx` (`tb_produto_idproduto` ASC, `tb_produto_categoria_idcategoria` ASC) VISIBLE,
  INDEX `fk_tb_cliente_has_tb_produto_tb_cliente1_idx` (`tb_cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_cliente_has_tb_produto_tb_cliente1`
    FOREIGN KEY (`tb_cliente_idcliente`)
    REFERENCES `banco_mercado`.`tb_cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cliente_has_tb_produto_tb_produto1`
    FOREIGN KEY (`tb_produto_idproduto` , `tb_produto_categoria_idcategoria`)
    REFERENCES `banco_mercado`.`tb_produto` (`idproduto` , `categoria_idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
